name: "CodeQL"

on:
  push:
    branches: ["main", "package-registry"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "42 0 * * 3"

jobs:
  analyze:
    name: Analyze
    runs-on: "ubuntu-latest"
    permissions:
      security-events: write
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: ["csharp"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Authenticate to NuGet registry
        run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/NAMESPACE/index.json"

      - name: Build with dotnet
        run: dotnet build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
